services:
  - type: web
    name: bookbuddy-qpi
    env: node
    plan: free
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookbuddy-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production

databases:
  - name: bookbuddy-db
    plan: free 